
#开发环境的配置
#配置MySQL的连接
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/goods_oa?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    #配置Druid连接池
    druid:
      url: jdbc:mysql://127.0.0.1:3306/goods_oa?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
  profiles: dev

---
#生成环境的配置
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/goods_oa?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  profiles: prod